# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBranchcut < Formula
  desc "A Git branch cleanup addon, branchcut."
  homepage "https://github.com/dlsrb6342/branchcut"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dlsrb6342/git-branchcut/releases/download/v0.0.1/git-branchcut_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "83eea825203318c3b318ede153d661677e355aa5177d6d65c9a3e2f0d04235e6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dlsrb6342/git-branchcut/releases/download/v0.0.1/git-branchcut_0.0.1_Linux_x86_64.tar.gz"
    sha256 "a55aa862c5ac64ff7d14652ee9b201743eb3936c73551c31575161e41fd2e695"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dlsrb6342/git-branchcut/releases/download/v0.0.1/git-branchcut_0.0.1_Linux_arm64.tar.gz"
    sha256 "f4aa7e5024dca58409a6c6f563ba08ec985af604d0d8cc430602a63e4e469f2f"
  end

  head "https://github.com/dlsrb6342/branchcut"

  depends_on "git"

  def install
    bin.install "git-branchcut"
  end

  def caveats; <<~EOS
    git-branchcut --help
  EOS
  end
end
